import { act, renderHook, waitFor } from "@testing-library/react";
import { describe, beforeEach, expect, it, vi } from "vitest";
import type { MySegmentHistoryResponse } from "@shared/types/segment-history";
import { useMySegmentHistory } from "./useMySegmentHistory";
const mocks = vi.hoisted(() => ({ uid: "owner" as string | null, services: {}, load: vi.fn() }));
vi.mock("../contexts/AuthContext", () => ({ useAuth: () => ({ user: mocks.uid ? { uid: mocks.uid } : null }) }));
vi.mock("../contexts/FirebaseServicesContext", () => ({ useFirebaseServices: () => mocks.services }));
vi.mock("../services/segmentHistory", () => ({ loadMySegmentHistory: mocks.load }));
const selection = { activityId: "a", effortId: "e", nonce: 1 };
const response = (id = "e", more = false) => ({ state: "available", inputRevision: "a".repeat(64), attempts: [{ effortId: id }], nextCursor: more ? "next" : null, coverage: { complete: false } }) as MySegmentHistoryResponse;
beforeEach(() => { mocks.uid = "owner"; mocks.services = {}; mocks.load.mockReset().mockResolvedValue(response()); });
describe("lazy owner history lifecycle", () => {
  it("does not read before selection, login or deployment enablement", () => { const { rerender } = renderHook(({ selected, enabled }) => useMySegmentHistory("s", selected, enabled), { initialProps: { selected: null as typeof selection | null, enabled: false } }); rerender({ selected: selection, enabled: false }); mocks.uid = null; rerender({ selected: selection, enabled: true }); expect(mocks.load).not.toHaveBeenCalled(); });
  it("sends explicit current effort and at most50, appends bound cursor without complete inference", async () => { mocks.load.mockResolvedValueOnce(response("e", true)).mockResolvedValueOnce(response("b")); const { result } = renderHook(() => useMySegmentHistory("s", selection, true)); await waitFor(() => expect(result.current.rows).toHaveLength(1)); act(() => result.current.loadMore()); await waitFor(() => expect(result.current.rows).toHaveLength(2)); expect(mocks.load.mock.calls[1]?.[2]).toMatchObject({ currentEffortId: "e", pageSize: 50, cursor: "next", expectedInputRevision: "a".repeat(64) }); expect(result.current.response?.coverage.complete).toBe(false); });
  it.each(["owner", "segment", "services"])("never resurrects completed results through %s ABA", async field => { const { result, rerender } = renderHook(({ segment }) => useMySegmentHistory(segment, selection, true), { initialProps: { segment: "s" } }); await waitFor(() => expect(result.current.rows).toHaveLength(1)); mocks.load.mockImplementation(() => new Promise(() => {})); if (field === "owner") mocks.uid = "other"; if (field === "services") mocks.services = {}; rerender({ segment: field === "segment" ? "other" : "s" }); mocks.uid = "owner"; if (field === "services") mocks.services = {}; rerender({ segment: "s" }); expect(result.current.rows).toEqual([]); expect(result.current.loading).toBe(true); });
  it("ignores late stale selection response and duplicate pagination rows", async () => { let resolve!: (r: MySegmentHistoryResponse) => void; mocks.load.mockReturnValueOnce(new Promise(r => { resolve = r; })).mockResolvedValueOnce(response("new", true)).mockResolvedValueOnce(response("new")); const { result, rerender } = renderHook(({ selected }) => useMySegmentHistory("s", selected, true), { initialProps: { selected: selection } }); rerender({ selected: { ...selection, nonce: 2 } }); await waitFor(() => expect(result.current.rows[0]?.effortId).toBe("new")); await act(async () => resolve(response("old"))); expect(result.current.rows[0]?.effortId).toBe("new"); act(() => result.current.loadMore()); await waitFor(() => expect(result.current.error).toBe(true)); expect(result.current.response).toBeNull(); });
});
