import type { DataFieldType } from "@shared/types/deviceSettings";

/**
 * DataFieldType → i18n key (settings namespace, dataField.* prefix).
 * 번역은 소비처(LayoutEditorCard 등)에서 `t(DATA_FIELD_LABEL_KEYS[type])` 로 수행한다.
 * App `LayoutConfig.kt`의 R.string.field_* 키들과 1:1로 대응한다.
 */
export const DATA_FIELD_LABEL_KEYS: Record<DataFieldType, string> = {
  SPEED: "dataField.SPEED",
  CADENCE: "dataField.CADENCE",
  HEART_RATE: "dataField.HEART_RATE",
  POWER: "dataField.POWER",
  V_POWER: "dataField.V_POWER",
  DISTANCE: "dataField.DISTANCE",
  TIME: "dataField.TIME",
  CLOCK: "dataField.CLOCK",
  CALORIES: "dataField.CALORIES",
  ELEVATION: "dataField.ELEVATION",
  GRADIENT: "dataField.GRADIENT",
  EMPTY: "dataField.EMPTY",
  AVG_SPEED: "dataField.AVG_SPEED",
  MAX_SPEED: "dataField.MAX_SPEED",
  AVG_POWER: "dataField.AVG_POWER",
  MAX_POWER: "dataField.MAX_POWER",
  AVG_CADENCE: "dataField.AVG_CADENCE",
  MAX_CADENCE: "dataField.MAX_CADENCE",
  AVG_HR: "dataField.AVG_HR",
  MAX_HR: "dataField.MAX_HR",
  AVG_SPEED_5MIN: "dataField.AVG_SPEED_5MIN",
  SPEED_VS_AVG: "dataField.SPEED_VS_AVG",
  TOTAL_ASCENT: "dataField.TOTAL_ASCENT",
  TOTAL_DESCENT: "dataField.TOTAL_DESCENT",
  VAM: "dataField.VAM",
  ELAPSED_TIME: "dataField.ELAPSED_TIME",
  STOPPED_TIME: "dataField.STOPPED_TIME",
  LAP_NUMBER: "dataField.LAP_NUMBER",
  LAP_DISTANCE: "dataField.LAP_DISTANCE",
  LAP_TIME: "dataField.LAP_TIME",
  LAST_LAP_TIME: "dataField.LAST_LAP_TIME",
  LAST_LAP_AVG_SPEED: "dataField.LAST_LAP_AVG_SPEED",
  NP: "dataField.NP",
  IF_FACTOR: "dataField.IF_FACTOR",
  TSS: "dataField.TSS",
  POWER_3S: "dataField.POWER_3S",
  POWER_10S: "dataField.POWER_10S",
  POWER_30S: "dataField.POWER_30S",
  TOTAL_ENERGY: "dataField.TOTAL_ENERGY",
  WBAL: "dataField.WBAL",
  WBAL_PERCENT: "dataField.WBAL_PERCENT",
  HR_ZONE: "dataField.HR_ZONE",
  POWER_ZONE: "dataField.POWER_ZONE",
  CADENCE_ZONE: "dataField.CADENCE_ZONE",
  GEAR: "dataField.GEAR",
  GEAR_RATIO: "dataField.GEAR_RATIO",
  GEAR_BATTERY: "dataField.GEAR_BATTERY",
  SHIFT_COUNT: "dataField.SHIFT_COUNT",
  CROSS_CHAIN: "dataField.CROSS_CHAIN",
  CLIMB_DISTANCE_REMAINING: "dataField.CLIMB_DISTANCE_REMAINING",
  CLIMB_ELEVATION_REMAINING: "dataField.CLIMB_ELEVATION_REMAINING",
  CLIMB_GRADIENT: "dataField.CLIMB_GRADIENT",
  CLIMB_CATEGORY: "dataField.CLIMB_CATEGORY",
  CLIMB_PROGRESS: "dataField.CLIMB_PROGRESS",
  CLIMB_NAME: "dataField.CLIMB_NAME",
  NEXT_CLIMB_DISTANCE: "dataField.NEXT_CLIMB_DISTANCE",
  NEXT_CLIMB_NAME: "dataField.NEXT_CLIMB_NAME",
  ROUTE_REMAINING: "dataField.ROUTE_REMAINING",
  ROUTE_REMAINING_ASCENT: "dataField.ROUTE_REMAINING_ASCENT",
  ETA: "dataField.ETA",
  SEGMENT_TIME_DELTA: "dataField.SEGMENT_TIME_DELTA",
  SEGMENT_PROGRESS: "dataField.SEGMENT_PROGRESS",
  SEGMENT_ELAPSED: "dataField.SEGMENT_ELAPSED",
  TEMPERATURE: "dataField.TEMPERATURE",
  WIND_SPEED: "dataField.WIND_SPEED",
  WIND_DIRECTION: "dataField.WIND_DIRECTION",
  HUMIDITY: "dataField.HUMIDITY",
  PRECIPITATION: "dataField.PRECIPITATION",
  WEATHER_CODE: "dataField.WEATHER_CODE",
  PEDAL_BALANCE: "dataField.PEDAL_BALANCE",
  TORQUE_EFFECTIVENESS: "dataField.TORQUE_EFFECTIVENESS",
  POWER_PHASE: "dataField.POWER_PHASE",
  POWER_PHASE_ARC: "dataField.POWER_PHASE_ARC",
  PEAK_TORQUE_ANGLE: "dataField.PEAK_TORQUE_ANGLE",
  MAX_FORCE: "dataField.MAX_FORCE",
  CRANK_CADENCE: "dataField.CRANK_CADENCE",
  PHONE_BATTERY: "dataField.PHONE_BATTERY",
  GPS_ACCURACY: "dataField.GPS_ACCURACY",
  HEADING: "dataField.HEADING",
  SUNRISE: "dataField.SUNRISE",
  SUNSET: "dataField.SUNSET",
  RADAR: "dataField.RADAR",
  RADAR_THREAT: "dataField.RADAR_THREAT",
  RADAR_VEHICLE_COUNT: "dataField.RADAR_VEHICLE_COUNT",
  RADAR_CLOSEST_DISTANCE: "dataField.RADAR_CLOSEST_DISTANCE",
  RADAR_APPROACH_SPEED: "dataField.RADAR_APPROACH_SPEED",
  RADAR_TOTAL_VEHICLES: "dataField.RADAR_TOTAL_VEHICLES",
  ACTION_CAM_BATTERY: "dataField.ACTION_CAM_BATTERY",
  ACTION_CAM_REC: "dataField.ACTION_CAM_REC",
  ACTION_CAM_MODE: "dataField.ACTION_CAM_MODE",
  ACTION_CAM_PHOTO: "dataField.ACTION_CAM_PHOTO",
  ACTION_CAM_RECORD: "dataField.ACTION_CAM_RECORD",
};

/**
 * UI에서 카테고리별로 묶어 보여주기 위한 그룹.
 * title은 i18n 키(settings namespace, layout.group* 접두사).
 * App `LayoutConfig.kt` 코드의 주석 카테고리 분류와 대체로 일치.
 */
export interface FieldGroup {
  titleKey: string;
  fields: DataFieldType[];
}

export const DATA_FIELD_GROUPS: FieldGroup[] = [
  {
    titleKey: "layout.groupBasic",
    fields: [
      "SPEED",
      "CADENCE",
      "HEART_RATE",
      "POWER",
      "V_POWER",
      "DISTANCE",
      "TIME",
      "CLOCK",
      "CALORIES",
      "ELEVATION",
      "GRADIENT",
    ],
  },
  {
    titleKey: "layout.groupAvgMax",
    fields: [
      "AVG_SPEED",
      "MAX_SPEED",
      "AVG_POWER",
      "MAX_POWER",
      "AVG_CADENCE",
      "MAX_CADENCE",
      "AVG_HR",
      "MAX_HR",
      "AVG_SPEED_5MIN",
      "SPEED_VS_AVG",
    ],
  },
  {
    titleKey: "layout.groupElevationTime",
    fields: ["TOTAL_ASCENT", "TOTAL_DESCENT", "VAM", "ELAPSED_TIME", "STOPPED_TIME"],
  },
  {
    titleKey: "layout.groupLap",
    fields: [
      "LAP_NUMBER",
      "LAP_DISTANCE",
      "LAP_TIME",
      "LAST_LAP_TIME",
      "LAST_LAP_AVG_SPEED",
    ],
  },
  {
    titleKey: "layout.groupTraining",
    fields: [
      "NP",
      "IF_FACTOR",
      "TSS",
      "POWER_3S",
      "POWER_10S",
      "POWER_30S",
      "TOTAL_ENERGY",
      "WBAL",
      "WBAL_PERCENT",
      "HR_ZONE",
      "POWER_ZONE",
      "CADENCE_ZONE",
    ],
  },
  {
    titleKey: "layout.groupGearPower",
    fields: [
      "GEAR",
      "GEAR_RATIO",
      "GEAR_BATTERY",
      "SHIFT_COUNT",
      "CROSS_CHAIN",
      "PEDAL_BALANCE",
      "TORQUE_EFFECTIVENESS",
      "POWER_PHASE",
      "POWER_PHASE_ARC",
      "PEAK_TORQUE_ANGLE",
      "MAX_FORCE",
      "CRANK_CADENCE",
    ],
  },
  {
    titleKey: "layout.groupClimbRoute",
    fields: [
      "CLIMB_DISTANCE_REMAINING",
      "CLIMB_ELEVATION_REMAINING",
      "CLIMB_GRADIENT",
      "CLIMB_CATEGORY",
      "CLIMB_PROGRESS",
      "CLIMB_NAME",
      "NEXT_CLIMB_DISTANCE",
      "NEXT_CLIMB_NAME",
      "ROUTE_REMAINING",
      "ROUTE_REMAINING_ASCENT",
      "ETA",
      "SEGMENT_TIME_DELTA",
      "SEGMENT_PROGRESS",
      "SEGMENT_ELAPSED",
    ],
  },
  {
    titleKey: "layout.groupWeatherSystem",
    fields: [
      "TEMPERATURE",
      "WIND_SPEED",
      "WIND_DIRECTION",
      "HUMIDITY",
      "PRECIPITATION",
      "WEATHER_CODE",
      "PHONE_BATTERY",
      "GPS_ACCURACY",
      "HEADING",
      "SUNRISE",
      "SUNSET",
    ],
  },
  {
    titleKey: "layout.groupRadarCam",
    fields: [
      "RADAR",
      "RADAR_THREAT",
      "RADAR_VEHICLE_COUNT",
      "RADAR_CLOSEST_DISTANCE",
      "RADAR_APPROACH_SPEED",
      "RADAR_TOTAL_VEHICLES",
      "ACTION_CAM_BATTERY",
      "ACTION_CAM_REC",
      "ACTION_CAM_MODE",
      "ACTION_CAM_PHOTO",
      "ACTION_CAM_RECORD",
    ],
  },
  {
    titleKey: "layout.groupMisc",
    fields: ["EMPTY"],
  },
];
